### ISSUE TITLE
Actions v2 and fetch-depth

### ISSUE THREAD

**Issue by NanoSector** [WyriHaximus/github-action-composer.lock-diff#36]
According to the documentation of https://github.com/actions/checkout

```
    # Number of commits to fetch. 0 indicates all history for all branches and tags.
    # Default: 1
    fetch-depth: ''
```

Perhaps this action would work with a fetch-depth of 0?  checkout v2 has numerous other improvements so moving to v1 might not be possible for everyone.

**Comment by WyriHaximus** [comment]
It's on my list of things to check. When developing this action v2 required a lot of hassle to get to work, and v1 "just works". Another thing is that, preferably the usage is exactly is shown in the readme container in it's own workflow due to the permissions required. Using v1 isolated from any other workflows shouldn't be an issue for anyone, unless I'm missing something that make using v2 required in certain cases.

**Comment by Yoshi2889** [comment]
The [pre-commit action](https://github.com/pre-commit/action) has similar issues but with private repositories, and setting the fetch-depth works for them. Might be worth taking a look at their approach.

**Comment by WyriHaximus** [comment]
Will have a look now that most of it is stable. IIRC the main issue I ran into was that not all heads where fetched, and not sure if fetch-deps `0` will resolve that. IIRC it doesn't

**Comment by WyriHaximus** [comment]
Closing this as this isn't an issue anymore with v2
